# Generated by Django 4.2.3 on 2023-11-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("encyclopedia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="id",
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
