# Generated by Django 4.2.3 on 2023-11-06 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("encyclopedia", "0003_article"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="Entry",
        ),
    ]
